CREATE EXTENSION IF NOT EXISTS vector;

GRANT ALL PRIVILEGES ON SCHEMA public TO popcornium;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO popcornium;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO popcornium;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO popcornium;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO popcornium;

SELECT 'PostgreSQL with pgvector initialized successfully!' as status;